# Use powerline
USE_POWERLINE="true"
# Has weird character width
# Example:
#    is not a diamond
HAS_WIDECHARS="false"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  source /usr/share/zsh/manjaro-zsh-prompt
fi

# alias                                              
[ -f ~/.config/zsh/aliases.zsh ] && source ~/.config/zsh/aliases.zsh 

# proxy                                              
[ -f ~/.config/zsh/proxy_git.zsh ] && source ~/.config/zsh/proxy_git.zsh 

#fzf                                                       
source $HOME/.config/zsh/fzf.zsh                           
source $HOME/.config/zsh/completion.zsh                    
source $HOME/.config/zsh/key-bindings.zsh
