#!/bin/bash
# 本地
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#settings github
export http_proxy="http://127.0.0.1:38457"
export https_proxy="http://127.0.0.1:38457"

# 设置屏幕分辨率
#xrandr --output Virtual-1 --mode 1920x1080 --rate 60.00
mpd &
dunst &
numlockx &
# 启动dwm
exec slstatus &
exec dwm
